# Azure pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none

trigger:
  branches:
    include:
    - 'release/*'
  paths:
    include:
    - 'src/Technosoftware/' 

stages:
- stage: nugetrc
  displayName: 'Push Nuget Release'
  jobs:
  - template: .azurepipelines/release.yml
    parameters:
      upload: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
      config: 'Release'
