# Azure pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: 
  autoCancel: 'true'
  branches:
    include:
    - '*'
  paths:
    include:
    - '*' 
    exclude:
    - 'bin/*' 
    - 'build/*' 
    - 'doc/*' 
    - 'documentation/*' 
    - 'Keys/*' 
    - 'tools/*' 
    - 'examples/net/*' 
    - 'Workshop/*' 
    - 'README.md' 

stages:
- stage: build
  displayName: 'Build Samples'
  jobs:
  - template: .azurepipelines/ci.yml
- stage: solutions
  dependsOn: []
  displayName: 'Build Solutions'
  jobs:
  - template: .azurepipelines/sln.yml